### ISSUE TITLE
[BUG] Search Page state 관리 문제

### ISSUE THREAD

**Issue by hong-soohyuk** [grooteogi/frontend#68]
## Bug
[Violation] Forced reflow while executing JavaScript took 51ms

## 설명
search page에서 search menu - search button으로 클릭된 버튼 아이디를 전달하는데,
1. 새로고침 되었을때 버튼을 클릭하면 첫번째 클릭에는 반응하지 않고, 두번째 클릭부터 버튼이 활성화되는 버그가 있음.
2. 위와 같이 크롬 콘솔에 warning이 나타남.

구조적으로 문제가 있는거 같은데 어떻게 변경해야할지...
구조 설명
in SearchMenu.tsx
```
  const [clickedButtonId, setClickedButtonId] = useState<number>(-1);
  ...
   <SearchButton
              fetchedTag={hash}
              clickedButtonId={clickedButtonId}
              setClickedButtonId={setClickedButtonId}
              key={hash.id}
            />
```

in SearchButton.tsx
```
interface SearchButtonProp extends ButtonProps {
  fetchedTag: fetchedHashtag;
  clickedButtonId: number;
  setClickedButtonId: (hashtagId: number) => void;
}
...
    <Styled.button
      onClick={() => {
        clickedButtonId === fetchedTag.id ? setClickedButtonId(-1) : setClickedButtonId(fetchedTag.id);
        // 버튼이 이미 눌린 상태일때 다시 누르면 state를 default인 -1로 설정. clicked가 버튼 각각의 id와 -1은 다르기때문에 비활성화됨.
      }}
      clicked={clickedButtonId === fetchedTag.id}
    >
```
그리고 하나 더 문제가 있는데,
3. clickedButtonId를 페이지에서 가지고있어야 axios 콜을 할텐데, 그렇게 되면 수평 스크롤(ButtonMenu)도 리 렌더링이 되어서 버튼 클릭마다 스크롤이 맨 앞으로 돌아가는 문제가 있음.

**Comment by Chloekkk** [comment]
지금까지 한 내용 푸쉬올려주시고 브랜치명 코멘트나 카톡으로 주시면 한번 코드로 봐볼게요! 글로는 문제점이 정확하게 인지되지 않아서요
